name: Deploy to Linux Server
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and deploy Django project
        uses: ssh-actions/ssh-command@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          run: |
            cd /path/to/project
            git pull origin main
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart gunicorn.service
      - name: List all files
        run: ls